### ISSUE TITLE
How to build

### ISSUE THREAD

**Issue by jspeckman** [mfranberg/libplinkio#31]
How do you build the C library?
The small blurb in the readme says to run configure, but there is no configure script, only the Makefile.am and .in

THanks

**Comment by mfranberg** [comment]
Sorry, I have been slow to update the README, it is using cmake nowadays. You can build it using:

```shell
mkdir build
cd build
cmake ../
make
```

**Comment by jspeckman** [comment]
Thanks!  That got me a little further.
When I run make, it complains there is no csv.h file.
Is there a list of dependencies that I need in order to build? (it's possible I just didn't see it)

**Comment by mfranberg** [comment]
Hmm, libcsv is already included in the sources, can you post the commands and the full output.

**Comment by jspeckman** [comment]
I looked through the source, but do not have any libcsv files.
I'll try pointing to an external copy to see if it fairs better.

cmake ../
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- The C compiler identification is GNU 10.3.0
-- The CXX compiler identification is GNU 10.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/oscer/software/GCCcore/10.3.0/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/oscer/software/GCCcore/10.3.0/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.20)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: /opt/oscer/easybuild_local/easyconfigs/libplinkio-master/src/build

[jason@c293 build]$ make
[  5%] Building C object CMakeFiles/libplinkio-static.dir/bed.o
[ 10%] Building C object CMakeFiles/libplinkio-static.dir/bed_header.o
[ 15%] Building C object CMakeFiles/libplinkio-static.dir/bim.o
[ 20%] Building C object CMakeFiles/libplinkio-static.dir/bim_parse.o
/opt/oscer/easybuild_local/easyconfigs/libplinkio-master/src/bim_parse.c:12:10: fatal error: csv.h: No such file or directory
   12 | #include <csv.h>
      |          ^~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/libplinkio-static.dir/bim_parse.o] Error 1
make[1]: *** [CMakeFiles/libplinkio-static.dir/all] Error 2
make: *** [all] Error 2

**Comment by jspeckman** [comment]
I agree, I just looked at the source on git again, and libcsv is there.
However, my copy does not include it.  I downloaded from the repo with the download zip file option on the web page, I believe I was on the master branch when I did.
I will try getting another copy of the master branch.

cmake version: 3.20.1

**Comment by jspeckman** [comment]
Ok, I just looked at my copy again (which is master) and I do have the libs, they just aren't built.
Do they need to be built separately beforehand, or is the main build process supposed to build everything?

**Comment by mfranberg** [comment]
All should be built during the build process, don't need to do anything separately.

I can't reproduce the error, I tried:
* Downloading from the "Code" dropdown, and the build commands worked
* Downloading from the latest release, and the build commands worked
* Checking out latest master with git, and the build commands worked

Your cmake is newer than mine, so it should work well. I guess there is something in your environment that I have not accounted for in the build script. I only have access to a mac environment right now, it looks like you are using some linux environment, so it could be some issue that have gone undiscovered.

**Comment by mfranberg** [comment]
Running the latest commit in github actions builds for mac, ubuntu and windows, and it went through fine as well 8 min ago.

**Comment by jspeckman** [comment]
Ok, I think I found the problem.
I had made the build directory in the src directory, and not in the top level libplinkio-master directory.
After doing that, I ran cmake ../ from the build directory, then I had to cd .. to run make.
I now have a libplinkio.so file in the src directory, so it looks like it worked.

Yes, I'm on a redhat 7 machine.

Thanks for your help.

**Comment by mfranberg** [comment]
Great to hear that you found the issue! I updated the docs: https://github.com/mfranberg/libplinkio/commit/345c06ffe25a1d37585b3a9f54fcd92f3b7f2b31

So I will close this issue now, good luck!
